---
- name: Deploy SSH keys and known_hosts
  hosts: localhost
  vars_prompt:
    - name: "vault_password"
      prompt: "Enter the Vault password"
      private: yes

  tasks:
    - name: Ensure .ssh directory exists
      file:
        dest: "{{ lookup('env', 'HOME') }}/.ssh"
        mode: 0700
        state: directory
      tags:
        - dotfiles
        - install
        - ssh

    - name: Decrypt and copy SSH private keys
      ansible.builtin.command: >
        ansible-vault decrypt
        --vault-password-file /tmp/vault_pass_file
        --output {{ lookup('env', 'HOME') }}/.ssh/{{ item | basename }}
        {{ item }}
      with_items:
        - mittarv
        - personal
      tags:
        - dotfiles
        - install
        - ssh

    - name: Decrypt and copy SSH public keys
      ansible.builtin.command: >
        ansible-vault decrypt
        --vault-password-file /tmp/vault_pass_file
        --output {{ lookup('env', 'HOME') }}/.ssh/{{ item | basename }}
        {{ item }}
      with_items:
        - mittarv.pub
        - personal.pub
      tags:
        - dotfiles
        - install
        - ssh

    - name: Decrypt and copy known_hosts file
      ansible.builtin.command: >
        ansible-vault decrypt
        --vault-password-file /tmp/vault_pass_file
        --output {{ lookup('env', 'HOME') }}/.ssh/known_hosts
        known_hosts
      tags:
        - dotfiles
        - install
        - ssh

    - name: Set authorized keys from files
      authorized_key:
        user: "{{ lookup('env', 'USER') }}"
        state: present
        key: "{{ lookup('env', 'HOME') }}/.ssh/{{ item }}"
      with_fileglob:
        - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
      tags:
        - dotfiles
        - install
        - ssh

    - name: Clean up temporary vault password file
      file:
        path: /tmp/vault_pass_file
        state: absent
      tags:
        - cleanup

  pre_tasks:
    - name: Create temporary vault password file
      copy:
        content: "{{ vault_password }}"
        dest: /tmp/vault_pass_file
        mode: 0600
      tags:
        - init

