---
- name: Add flatpak PPA
  apt_repository:
    repo: "ppa:alexlarsson/flatpak"
    state: present

- name: Install flatpak and flatpak-builder
  apt:
    package: [flatpak, flatpak-builder]
    update_cache: yes
    state: present
...
