- name: "i3 | Install"
  ansible.builtin.apt:
    name: i3-wm 
    state: latest 
  become: true

- name: "i3 | Ensure i3 directory structure exists"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - ~/.config
    - ~/.config/i3

- name: "i3 | Copy i3 config"
  ansible.builtin.copy:
    src: config
    dest: ~/.config/i3/config
    mode: "0644"

