---
- name: "Git | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

- name: "Git | Set user.name and user.email"
  ansible.builtin.git_config:
    scope: global
    name: user.name
    value: "{{ git_user_name }}"
  when: git_user_name is defined
