---
# TODO: Use a PPA/other source w/ automatic updates once provided by upstream
- name: Get latest Alacritty .deb URL
  # Ignore linter warning abot wget - it's cleaner than the alternative.
  args:
    warn: false
  shell: wget --quiet https://github.com/jwilm/alacritty/releases -O- | grep "_amd64.deb" | grep release | cut -d '"' -f2 | head -1 | sed "s/^/https:\/\/github.com/"
  register: alacritty_latest_deb_url
  failed_when: alacritty_latest_deb_url.rc > 0
  changed_when: false

- name: Install alacritty
  apt:
    deb: "{{ alacritty_latest_deb_url.stdout }}"
    state: present

- name: Copy Alacritty config into .config/alacritty 
  block:
    - name: Check to see if $HOME/.config/alacritty exists
      ansible.builtin.stat:
        path: $HOME/.config/alacritty 
      register: alacritty_dir

    - name: Ensure alacritty_dir exists
      ansible.builtin.shell:
        cmd: New-Item -ItemType Directory -Path "$HOME/.config/alacritty" -ErrorAction SilentlyContinue
      failed_when: false
      args:
        executable: 
      when: alacritty_dir.stat.exists == false

    - name: Copy Alacritty config
      ansible.builtin.copy:
        src: ubuntu_alacritty.toml
        dest: $HOME/.config/alacritty/alacritty.toml 
